import "server-only";
import type { ExplanationKey } from "../explanation";

export const ANSWER_KEYS: Record<string, ExplanationKey> = {
  "q-price-whole": {
    correctChoiceId: "b",
    canonicalExplanation:
      "Company A costs 8 dollars times 1 billion shares, which is $8 billion for the whole business. Company B costs 80 dollars times 10 million shares, which is $800 million. Both earned $40 million. A’s price is 200 times that profit. B’s price is 20 times that profit. B is the lower comparison. A lower comparison still does not mean B is a better investment.",
    ruleOfThumb: "Price the whole business, then divide by yearly profit.",
    exception: "A lower multiple alone does not establish a better investment.",
    understoodIfCorrect: "You compared the whole businesses instead of stopping at $8 versus $80.",
    missingIfWrong: "The share sticker is not the price of the business.",
    misconceptionByChoice: {
      a: "share_price_is_the_business_price",
      b: null,
      c: "share_price_is_the_business_price",
      d: "fame_or_popularity_is_evidence",
    },
    supportPhrases: ["whole", "market", "billion", "800", "times", "multiple", "p/e", "profit"],
    contradictionPhrases: ["$8 is less", "8 is less", "share price is lower", "company a is cheaper", "sticker"],
  },
  "q-price-whole-transfer": {
    correctChoiceId: "b",
    canonicalExplanation:
      "Cafe North costs 4 × 50 million = $200 million. Cafe South costs 40 × 2 million = $80 million. Both earned $2 million, so North is 100 times profit and South is 40 times profit. South is the lower comparison. That still is not a buy or sell instruction.",
    ruleOfThumb: "Multiply price by share count before you call something cheap.",
    exception: "The lower multiple is not a full investment case.",
    understoodIfCorrect: "You priced each whole cafe before comparing profit.",
    missingIfWrong: "A $4 share can belong to a more expensive business.",
    misconceptionByChoice: {
      a: "share_price_is_the_business_price",
      b: null,
      c: "share_price_is_the_business_price",
      d: "fame_or_popularity_is_evidence",
    },
    supportPhrases: ["200", "80", "whole", "times", "profit", "million"],
    contradictionPhrases: ["4 is cheaper", "$4", "small share price"],
  },
  "q-price-equal": {
    correctChoiceId: "c",
    canonicalExplanation:
      "Company C is 20 × 50 million = $1 billion. Company D is 100 × 10 million = $1 billion. Each earned $10 million, so each whole price is 100 times profit. They match on this comparison.",
    ruleOfThumb: "Same whole price and same profit means the same multiple.",
    exception: "Equal multiples do not mean the businesses face the same risks.",
    understoodIfCorrect: "You noticed the whole prices match.",
    missingIfWrong: "Different stickers can still add up to the same business price.",
    misconceptionByChoice: {
      a: "share_price_is_the_business_price",
      b: "share_price_is_the_business_price",
      c: null,
      d: "fame_or_popularity_is_evidence",
    },
    supportPhrases: ["same", "both", "1 billion", "billion", "whole", "100"],
    contradictionPhrases: ["20 is cheaper", "higher share price means stronger"],
  },
  "q-price-equal-transfer": {
    correctChoiceId: "c",
    canonicalExplanation:
      "Before the split the whole business cost $500 million. After a 2-for-1 split it is 20 million shares at $25, which is still $500 million. Profit is still $25 million, so the comparison is unchanged.",
    ruleOfThumb: "A split changes the slice size, not the whole price, when nothing else changes.",
    exception: "If cash, debt, or profit also changes, you cannot blame or credit the split alone.",
    understoodIfCorrect: "You treated the split as a change in slicing.",
    missingIfWrong: "A lower sticker after a split is not a sale on the business.",
    misconceptionByChoice: {
      a: "share_price_is_the_business_price",
      b: "share_price_is_the_business_price",
      c: null,
      d: "share_price_is_the_business_price",
    },
    supportPhrases: ["same", "500", "split", "whole", "unchanged"],
    contradictionPhrases: ["fell from $50", "became cheaper"],
  },
  "q-diverse-airlines": {
    correctChoiceId: "b",
    canonicalExplanation:
      "The three airlines share fuel, routes, and demand for flights. A shock to air travel can hit all three. Counting names is not the same as spreading that risk.",
    ruleOfThumb: "Name the event that could hurt every holding at once.",
    exception: "A mixed basket can still fall together in a broad panic. Mixing is not a shield against every risk.",
    understoodIfCorrect: "You looked for a shared way to get hurt.",
    missingIfWrong: "Three tickers are not three independent bets when the business risk is the same.",
    misconceptionByChoice: {
      a: "more_holdings_means_diversified",
      b: null,
      c: "more_holdings_means_diversified",
      d: "fame_or_popularity_is_evidence",
    },
    supportPhrases: ["same", "together", "fuel", "travel", "all three", "shared"],
    contradictionPhrases: ["three companies are always", "ticker"],
  },
  "q-diverse-airlines-transfer": {
    correctChoiceId: "b",
    canonicalExplanation:
      "Ten suppliers that all live on one phone company’s orders share that customer. The long list does little to protect against a cut from that buyer.",
    ruleOfThumb: "Follow the shared customer, supplier, or rule.",
    exception: "The ten firms might still differ in other risks, such as their own debt.",
    understoodIfCorrect: "You traced the risk to one buyer.",
    missingIfWrong: "A longer list does not help when the cash comes from one place.",
    misconceptionByChoice: {
      a: "more_holdings_means_diversified",
      b: null,
      c: "more_holdings_means_diversified",
      d: "fame_or_popularity_is_evidence",
    },
    supportPhrases: ["customer", "buyer", "one", "same", "phone"],
    contradictionPhrases: ["ten is a lot", "guarantee"],
  },
  "q-diverse-credit": {
    correctChoiceId: "b",
    canonicalExplanation:
      "Different industries did not protect them against a lending freeze, because both needed to refinance. Ordinary differences do not hedge a risk they share.",
    ruleOfThumb: "Ask how each holding is financed when the risk is a credit freeze.",
    exception: "They might still diversify other risks, such as a strike that hits only one industry.",
    understoodIfCorrect: "You matched the shock to the shared loan need.",
    missingIfWrong: "Different products do not hedge a shock both balance sheets share.",
    misconceptionByChoice: {
      a: "calm_correlation_means_a_hedge",
      b: null,
      c: "calm_correlation_means_a_hedge",
      d: "calm_correlation_means_a_hedge",
    },
    supportPhrases: ["loan", "lend", "refinanc", "both", "credit", "debt"],
    contradictionPhrases: ["different industries always", "ordinary days"],
  },
  "q-diverse-credit-transfer": {
    correctChoiceId: "b",
    canonicalExplanation:
      "Quiet years hid a shared diesel cost. When fuel spiked, that shared input mattered more than the usual difference in their results.",
    ruleOfThumb: "Look for a shared input, not only a quiet history.",
    exception: "One bad stretch does not mean the two businesses are identical in every other way.",
    understoodIfCorrect: "You treated the fuel spike as a shared cost.",
    missingIfWrong: "A calm history is not proof of protection against a named shock.",
    misconceptionByChoice: {
      a: "calm_correlation_means_a_hedge",
      b: null,
      c: "calm_correlation_means_a_hedge",
      d: "calm_correlation_means_a_hedge",
    },
    supportPhrases: ["fuel", "diesel", "shared", "cost", "both"],
    contradictionPhrases: ["guarantee", "secretly"],
  },
  "q-cash-receivables": {
    correctChoiceId: "c",
    canonicalExplanation:
      "Cash from operations = 5 million − 6 million + 0 = negative 1 million. Profit counted sales the customers have not paid. Under the stated assumptions, the business used 1 million dollars of cash.",
    ruleOfThumb: "Subtract the rise in unpaid bills from profit when you want operating cash.",
    exception: "Growing unpaid bills can be normal. This identity does not say the studio cheated. It says cash and profit differed.",
    understoodIfCorrect: "You treated unpaid bills as profit that is not cash yet.",
    missingIfWrong: "Net income already includes sales that may not have been collected.",
    misconceptionByChoice: {
      a: "profit_is_cash",
      b: "profit_is_cash",
      c: null,
      d: "profit_is_cash",
    },
    supportPhrases: ["-1", "negative", "unpaid", "receiv", "not paid", "minus 6", "subtract"],
    contradictionPhrases: ["profit is cash", "same as profit"],
  },
  "q-cash-receivables-transfer": {
    correctChoiceId: "b",
    canonicalExplanation:
      "Cash from operations = 3 million − 1 million + 0.5 million = 2.5 million. Depreciation is added back because it reduced profit without cash leaving this year.",
    ruleOfThumb: "Add back non-cash expenses, and subtract profit that has not been collected.",
    exception: "This is a teaching identity with the other changes set to zero. Real statements have more lines.",
    understoodIfCorrect: "You used both the unpaid bills and the non-cash depreciation.",
    missingIfWrong: "Profit, unpaid bills, and depreciation are not interchangeable.",
    misconceptionByChoice: {
      a: "profit_is_cash",
      b: null,
      c: "profit_is_cash",
      d: "profit_is_cash",
    },
    supportPhrases: ["2.5", "depreciation", "unpaid", "add"],
    contradictionPhrases: ["profit is the cash"],
  },
  "q-cash-fcf": {
    correctChoiceId: "c",
    canonicalExplanation:
      "Free cash flow = 6 million of cash from operations − 7 million spent on vans = negative 1 million. Revenue and profit are different numbers and were not the inputs.",
    ruleOfThumb: "Free cash flow starts from operating cash, then subtracts cash spent on long-lived equipment.",
    exception: "Spending on vans might be a good decision. Negative free cash flow is not automatically a failing business.",
    understoodIfCorrect: "You used operating cash and the van purchase, not revenue.",
    missingIfWrong: "Sales and accounting profit are not the cash left after equipment.",
    misconceptionByChoice: {
      a: "revenue_is_profit",
      b: "profit_is_cash",
      c: null,
      d: "profit_is_cash",
    },
    supportPhrases: ["6", "7", "negative", "vans", "free cash"],
    contradictionPhrases: ["revenue", "the profit"],
  },
  "q-cash-fcf-transfer": {
    correctChoiceId: "d",
    canonicalExplanation:
      "Free cash flow = 8 million of cash from operations − 3 million of van spending = 5 million. Profit is also 5 million only by coincidence. Revenue is not the input.",
    ruleOfThumb: "Use operating cash minus equipment spending, even if profit happens to match the result.",
    exception: "A matching profit figure does not mean profit and free cash flow are the same idea.",
    understoodIfCorrect: "You subtracted van spending from operating cash.",
    missingIfWrong: "Revenue and accounting profit are not the definition you were given.",
    misconceptionByChoice: {
      a: "revenue_is_profit",
      b: "profit_is_cash",
      c: "profit_is_cash",
      d: null,
    },
    supportPhrases: ["8", "3", "vans", "operations"],
    contradictionPhrases: ["revenue is"],
  },
  "q-expect-beat": {
    correctChoiceId: "b",
    canonicalExplanation:
      "A 2% move after a small beat says the news was close to what buyers already expected. It is not a complete grade of the business, and it is not a buy or sell signal.",
    ruleOfThumb: "Read a price move as a surprise relative to the old price.",
    exception: "You cannot see the exact expectation from one day. Do not invent a full valuation from a 2% move.",
    understoodIfCorrect: "You separated surprise from business quality.",
    missingIfWrong: "A small move is not a verdict that the business is weak.",
    misconceptionByChoice: {
      a: "price_move_measures_quality",
      b: null,
      c: "good_business_means_good_price",
      d: "fame_or_popularity_is_evidence",
    },
    supportPhrases: ["surpris", "expect", "not a grade", "already", "news"],
    contradictionPhrases: ["must be weak", "sure investment"],
  },
  "q-expect-beat-transfer": {
    correctChoiceId: "a",
    canonicalExplanation:
      "An 18% move supports the narrower claim that the contract was a large surprise versus the prior price. It does not prove the factory is a better long-term business than another firm.",
    ruleOfThumb: "A big move is evidence about surprise, not a trophy for the whole business.",
    exception: "The contract might matter for years. That case needs more facts than the one-day move.",
    understoodIfCorrect: "You limited the claim to the surprise.",
    missingIfWrong: "A one-day percentage is not a comparison of long-term business quality.",
    misconceptionByChoice: {
      a: null,
      b: "price_move_measures_quality",
      c: "fame_or_popularity_is_evidence",
      d: "fame_or_popularity_is_evidence",
    },
    supportPhrases: ["surpris", "news", "prior", "old price", "relative"],
    contradictionPhrases: ["certainly a better", "cannot fall"],
  },
  "q-expect-two-prices": {
    correctChoiceId: "b",
    canonicalExplanation:
      "The same $5 of earnings is priced at 10 times on date one and 20 times on date two. The higher multiple is the larger claim about the future. It might be justified. It is still the higher expectation relative to current earnings.",
    ruleOfThumb: "Same current earnings and a higher price means a bigger bet on what comes next.",
    exception: "This year’s earnings might be unusually low or high, so the comparison can mislead if you ignore that.",
    understoodIfCorrect: "You treated the higher multiple as a stronger expectation, not as proof of a better buy.",
    missingIfWrong: "Equal earnings do not mean equal expectations when the prices differ.",
    misconceptionByChoice: {
      a: "lower_multiple_means_better_investment",
      b: null,
      c: "good_business_means_good_price",
      d: "fame_or_popularity_is_evidence",
    },
    supportPhrases: ["20", "higher", "future", "multiple", "expect"],
    contradictionPhrases: ["10 times is the higher expectation"],
  },
  "q-expect-two-prices-transfer": {
    correctChoiceId: "b",
    canonicalExplanation:
      "Shop A costs 8 times this year’s profit. Shop B costs 30 times this year’s profit. Relative to the only profit figure given, Shop B’s price asks you to believe more.",
    ruleOfThumb: "Divide the whole price by this year’s profit and compare.",
    exception: "A higher multiple can be fair if future profit really is much larger. You were not given that fact.",
    understoodIfCorrect: "You compared how many years of current profit each price represents.",
    missingIfWrong: "Same profit with a much higher price is not the same story.",
    misconceptionByChoice: {
      a: "lower_multiple_means_better_investment",
      b: null,
      c: "good_business_means_good_price",
      d: "share_price_is_the_business_price",
    },
    supportPhrases: ["30", "8", "times", "higher", "optimistic", "future"],
    contradictionPhrases: ["same story"],
  },
  "q-dilution-percent": {
    correctChoiceId: "b",
    canonicalExplanation:
      "The founder still holds 1,000,000 shares, but the company now has 2,000,000. Ownership is 1,000,000 / 2,000,000 = 50%. Keeping every old share did not keep 100%.",
    ruleOfThumb: "Divide your shares by all shares after the new ones exist.",
    exception: "50% of a company that received valuable cash can be worth more dollars than the old 100%. The fraction still fell.",
    understoodIfCorrect: "You updated the denominator.",
    missingIfWrong: "The share count in the drawer is not the ownership percentage.",
    misconceptionByChoice: {
      a: "same_share_count_means_same_ownership",
      b: null,
      c: "same_share_count_means_same_ownership",
      d: "same_share_count_means_same_ownership",
    },
    supportPhrases: ["50", "half", "2,000,000", "denominator", "new shares"],
    contradictionPhrases: ["still 100", "did not sell"],
  },
  "q-dilution-percent-transfer": {
    correctChoiceId: "b",
    canonicalExplanation:
      "You still own 200 shares. Total shares are 2,000. 200 / 2,000 = 10%.",
    ruleOfThumb: "New shares in the total change your percentage even when you sell nothing.",
    exception: "The print shop may be more valuable after the partner’s cash. That is a separate question from the percentage.",
    understoodIfCorrect: "You recalculated 200 divided by 2,000.",
    missingIfWrong: "Holding 200 shares is not the same as holding 20% after the total doubles.",
    misconceptionByChoice: {
      a: "same_share_count_means_same_ownership",
      b: null,
      c: "same_share_count_means_same_ownership",
      d: "same_share_count_means_same_ownership",
    },
    supportPhrases: ["10", "2,000", "200", "half"],
    contradictionPhrases: ["still 20"],
  },
  "q-dilution-eps": {
    correctChoiceId: "b",
    canonicalExplanation:
      "Earnings stay $10 million by assumption. Shares go from 10 million to 20 million. Profit per share goes from $1.00 to $0.50.",
    ruleOfThumb: "If profit is frozen and shares double, profit per share halves.",
    exception: "The new cash might raise profit in a later year. This question froze this year’s profit on purpose.",
    understoodIfCorrect: "You divided the same profit by the new share count.",
    missingIfWrong: "Profit per share uses the new count, not the old one.",
    misconceptionByChoice: {
      a: "same_share_count_means_same_ownership",
      b: null,
      c: "same_share_count_means_same_ownership",
      d: "profit_is_cash",
    },
    supportPhrases: ["0.50", "20 million", "half", "doubl"],
    contradictionPhrases: ["still $1", "same as before"],
  },
  "q-dilution-eps-transfer": {
    correctChoiceId: "b",
    canonicalExplanation:
      "Shares become 4,000 + 2,000 = 6,000. Earnings stay $12,000. 12,000 / 6,000 = $2.00 per share.",
    ruleOfThumb: "Divide this year’s profit by the share count after the issue.",
    exception: "Next year’s profit is not in the problem. Do not assume it.",
    understoodIfCorrect: "You used 6,000 shares, not the old 4,000.",
    missingIfWrong: "The old per-share figure ignores the new shares.",
    misconceptionByChoice: {
      a: "same_share_count_means_same_ownership",
      b: null,
      c: "revenue_is_profit",
      d: "same_share_count_means_same_ownership",
    },
    supportPhrases: ["2", "6,000", "12,000"],
    contradictionPhrases: ["$3"],
  },
  "q-thesis-mind": {
    correctChoiceId: "b",
    canonicalExplanation:
      "A thesis needs a fact that would change the author’s mind. Same-store sales falling for two years is one observable exit. Fame, a higher price, or louder confidence does not supply that fact.",
    ruleOfThumb: "Write the observation that would make you drop the claim.",
    exception: "Naming that fact does not make the original hope true or false. It makes the hope testable.",
    understoodIfCorrect: "You asked for an exit door made of evidence.",
    missingIfWrong: "Confidence and fame are not substitutes for a disconfirming fact.",
    misconceptionByChoice: {
      a: "fame_or_popularity_is_evidence",
      b: null,
      c: "price_move_measures_quality",
      d: "fame_or_popularity_is_evidence",
    },
    supportPhrases: ["change", "mind", "sales", "fact", "test", "wrong"],
    contradictionPhrases: ["famous investor", "exclamation"],
  },
  "q-thesis-mind-transfer": {
    correctChoiceId: "b",
    canonicalExplanation:
      "The repeat-purchase test is a way to drop the claim. It is not proof the brand will win, and it does not turn one floor’s taste into evidence.",
    ruleOfThumb: "A disconfirming test is progress even when the claim is still unproven.",
    exception: "A weak test — one you would explain away — is not a real exit.",
    understoodIfCorrect: "You saw testability without treating it as proof.",
    missingIfWrong: "Adding an exit condition does not make the prediction come true.",
    misconceptionByChoice: {
      a: "thesis_without_disconfirmation",
      b: null,
      c: "fame_or_popularity_is_evidence",
      d: "fame_or_popularity_is_evidence",
    },
    supportPhrases: ["change", "test", "drop", "fact", "if"],
    contradictionPhrases: ["proof that the brand will win", "guarantee"],
  },
  "q-thesis-challenge": {
    correctChoiceId: "c",
    canonicalExplanation:
      "The useful reply names two assumptions: enrollment keeps rising, and growth needs no new cash. It then asks about flat enrollment. Insults, a famous fund, and group-chat agreement do not test the claim.",
    ruleOfThumb: "Challenge the belief the thesis needs, and say which fact would pressure it.",
    exception: "A clean challenge can still be mistaken. It is not a verdict.",
    understoodIfCorrect: "You picked the reply that names an assumption.",
    missingIfWrong: "Fame, insults, and agreement are not evidence about the business.",
    misconceptionByChoice: {
      a: "fame_or_popularity_is_evidence",
      b: "fame_or_popularity_is_evidence",
      c: null,
      d: "fame_or_popularity_is_evidence",
    },
    supportPhrases: ["assumption", "enrollment", "capital", "cash", "if"],
    contradictionPhrases: ["group chat", "famous fund", "bad at this"],
  },
  "q-thesis-challenge-transfer": {
    correctChoiceId: "c",
    canonicalExplanation:
      "The comment isolates the free-labor assumption. That does not prove the app will fail, and it is not a personal attack or a popularity claim.",
    ruleOfThumb: "Naming the breaking point is a challenge, not yet a conclusion.",
    exception: "Volunteers might remain willing. The assumption can survive the challenge.",
    understoodIfCorrect: "You classified the comment as a test of an assumption.",
    missingIfWrong: "A pointed question is not the same as proof of failure.",
    misconceptionByChoice: {
      a: "fame_or_popularity_is_evidence",
      b: "thesis_without_disconfirmation",
      c: null,
      d: "fame_or_popularity_is_evidence",
    },
    supportPhrases: ["assumption", "not proof", "specific", "volunteers", "paid"],
    contradictionPhrases: ["will fail", "personal attack"],
  },
};

export function answerKey(questionId: string): ExplanationKey | undefined {
  return ANSWER_KEYS[questionId];
}
